# Should return 200 OK with body '{"status":"ok"}'
GET http://localhost:8080/healthz

###

# Should return 405 Method Not Allowed
POST http://localhost:8080/healthz

###

GET http://localhost:8080/tasks

###

GET http://localhost:8080/tasks/01a10221-4434-7f6c-ad33-0a630c171655

###

POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "ấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấấ"
}

###

DELETE http://localhost:8080/tasks/01a10221-4434-7f6c-ad33-0a630c171655