# Should return 200 OK with body '{"status":"ok"}'
GET http://localhost:8080/healthz

###

# Should return 405 Method Not Allowed
POST http://localhost:8080/healthz

###

GET http://localhost:8080/tasks
X-Request-ID: $$@$@$

###

GET http://localhost:8080/tasks/01a11a6d-43a4-7525-b28e-33c74e76a93b

###

POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "It's done",
  "due_at": "2026-10-08T07:29:21.090Z"
}

###

DELETE http://localhost:8080/tasks/01a10221-4434-7f6c-ad33-0a630c171655

###

PATCH http://localhost:8080/tasks/01a10702-4786-7326-94ef-a5d211a9ccdf
Content-Type: application/json

{
  "title": "Test updated 3"
}

###

GET http://localhost:8080/panic